### PR TITLE
Apply explicit API rules

### PR DESCRIPTION
**Pull request by lemnik**
## Goal
Apply the Kotlin compilers explicit api rules to the project in order to generally improve code readability and quality.

## Changeset
Nearly all of the files were touched by this change.

Not obviously part of the change was moving the `AutoInstrumentationCache` to the `internal` package, as it was never part of the public API.

## Testing
Relied on existing tests.

### CODE REVIEW

**Comment by tomlongridge** [comment]
There are a lot of things being declared public (e.g. the Attribute setter) that I'm not sure about – is this changing the visibility or just making it explicit?

**Comment by lemnik** [comment]
In the case of `public` the changes are simply making the visibility explicit (`public` is the default visibility in Kotlin).

**Review by tomlongridge — APPROVED** [review]

**Review by SmartbearYing — COMMENTED** [review]
Maybe add restrict rule to public classes and interfaces in Internal package

**Review by SmartbearYing — APPROVED** [review]
LGTM

**Pull request merged**
